server:
  port: 7001

spring:
  application:
    name: eurka-server

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/